[2025-07-25T19:54:05.196+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_receita_cnpj.executar_pipeline_cnpjs manual__2025-07-25T19:53:58.565406+00:00 [queued]>
[2025-07-25T19:54:05.249+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_receita_cnpj.executar_pipeline_cnpjs manual__2025-07-25T19:53:58.565406+00:00 [queued]>
[2025-07-25T19:54:05.251+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-25T19:54:05.314+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): executar_pipeline_cnpjs> on 2025-07-25 19:53:58.565406+00:00
[2025-07-25T19:54:05.383+0000] {standard_task_runner.py:60} INFO - Started process 45 to run task
[2025-07-25T19:54:05.395+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_receita_cnpj', 'executar_pipeline_cnpjs', 'manual__2025-07-25T19:53:58.565406+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_receita_cnpj.py', '--cfg-path', '/tmp/tmp_38u9a0d']
[2025-07-25T19:54:05.427+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask executar_pipeline_cnpjs
[2025-07-25T19:54:05.712+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_receita_cnpj.executar_pipeline_cnpjs manual__2025-07-25T19:53:58.565406+00:00 [running]> on host e7e111e48eb7
[2025-07-25T19:54:05.947+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_receita_cnpj' AIRFLOW_CTX_TASK_ID='executar_pipeline_cnpjs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T19:53:58.565406+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T19:53:58.565406+00:00'
[2025-07-25T19:54:05.955+0000] {etl_receita_cnpj.py:30} INFO - ðŸš€ Iniciando pipeline para CNPJ: 27865757000102
[2025-07-25T19:54:06.428+0000] {logging_mixin.py:188} INFO - âœ… Dados baixados: data/27865757000102.json
[2025-07-25T19:54:06.521+0000] {etl_receita_cnpj.py:44} INFO - âœ… JSON salvo em: data/27865757000102.json
[2025-07-25T19:54:06.564+0000] {logging_mixin.py:188} INFO - âœ… CSV gerado: data/27865757000102.csv
[2025-07-25T19:54:06.565+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_receita_cnpj.py", line 47, in pipeline_cnpjs
    gravar_em_mongo(cnpj, geral, socios, cnaes)
TypeError: gravar_em_mongo() takes from 1 to 2 positional arguments but 4 were given
[2025-07-25T19:54:06.600+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_receita_cnpj, task_id=executar_pipeline_cnpjs, execution_date=20250725T195358, start_date=20250725T195405, end_date=20250725T195406
[2025-07-25T19:54:06.634+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task executar_pipeline_cnpjs (gravar_em_mongo() takes from 1 to 2 positional arguments but 4 were given; 45)
[2025-07-25T19:54:06.696+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-25T19:54:06.837+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
